obj-y += entry/

obj-$(CONFIG_PERF_EVENTS) += events/

# Xen paravirtualization support
obj-$(CONFIG_XEN) += xen/

obj-$(CONFIG_PVH) += platform/pvh/

obj-y += realmode/
obj-y += kernel/
obj-y += mm/

obj-y += platform/

# for cleaning
subdir- += boot tools
